### ISSUE TITLE
When installing firedrake, run into PETSC issue

### ISSUE THREAD

**Issue by dmitryshribak** [dynamicslab/hydrogym#191]
Your issue content here.Traceback (most recent call last):
  File "/home/dmitry/Documents/DaiResearch/CT-Rep/Hydrogym_main/hydrogym/third_party/firedrake/scripts/firedrake-install", line 1851, in <module>
    install("petsc/")
  File "/home/dmitry/Documents/DaiResearch/CT-Rep/Hydrogym_main/hydrogym/third_party/firedrake/scripts/firedrake-install", line 1020, in install
    build_and_install_petsc()
  File "/home/dmitry/Documents/DaiResearch/CT-Rep/Hydrogym_main/hydrogym/third_party/firedrake/scripts/firedrake-install", line 1159, in build_and_install_petsc
    check_call([python, "./configure", "PETSC_DIR={}".format(petsc_dir), "PETSC_ARCH={}".format(petsc_arch)] + petsc_options)
  File "/home/dmitry/Documents/DaiResearch/CT-Rep/Hydrogym_main/hydrogym/third_party/firedrake/scripts/firedrake-install", line 653, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/home/dmitry/.pyenv/versions/3.10.13/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/dmitry/.pyenv/versions/3.10.13/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/dmitry/Documents/DaiResearch/CT-Rep/Hydrogym_main/hydrogym/third_party/firedrake/scripts/firedrake/bin/python', './configure', 'PETSC_DIR=/home/dmitry/Documents/DaiResearch/CT-Rep/Hydrogym_main/hydrogym/third_party/firedrake/scripts/firedrake/src/petsc', 'PETSC_ARCH=default', '--download-scalapack', '--download-mumps', '--download-hypre', '--download-metis', '--download-pnetcdf', '--download-hwloc', '--with-shared-libraries=1', '--download-ml', '--with-fortran-bindings=0', '--download-bison', '--download-cmake', '--download-suitesparse', '--download-eigen=/home/dmitry/Documents/DaiResearch/CT-Rep/Hydrogym_main/hydrogym/third_party/firedrake/scripts/firedrake/src/eigen-3.3.3.tgz ', '--download-netcdf', '--download-superlu_dist', '--download-mpich', '--download-hdf5', '--with-zlib', '--download-chaco', '--with-c2html=0', '--download-ptscotch', '--with-debugging=0', '--download-pastix']' returned non-zero exit status 1.

**Comment by jcallaham** [comment]
Closing, as this is an issue with Firedrake and not specifically Hydrogym. See the Firedrake docs and discussions for info there (though if you ask for help on Slack or GitHub, be sure to post enough information to reproduce the error, including system configuration, versions, etc).
