### ISSUE TITLE
ppo.py does not work out of box

### ISSUE THREAD

**Issue by dmitryshribak** [dynamicslab/hydrogym#192]
/IdeaProjects/hydrogym/examples/ppo/ppo.py:457: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:275.)
  a, v, logp = ac.step(torch.as_tensor(o, dtype=torch.float32))
Traceback (most recent call last):
  File "/IdeaProjects/hydrogym/examples/ppo/ppo.py", line 520, in <module>
    ppo(
  File "/IdeaProjects/hydrogym/examples/ppo/ppo.py", line 457, in ppo
    a, v, logp = ac.step(torch.as_tensor(o, dtype=torch.float32))
ValueError: expected sequence of length 17 at dim 1 (got 0)

**Comment by dmitryshribak** [comment]
firedrake/envs/cylinder/coarse.msh due to "No such file or directory"

**Comment by ludgerpaehler** [comment]
Already fixed on the linked PR prep branch - will auto-close with the merge of the PR.

**Comment by ludgerpaehler** [comment]
Working on main by now.
