### ISSUE TITLE
AttributeError: module 'hydrogym.firedrake' has no attribute 'IPCS'

### ISSUE THREAD

**Issue by dmitryshribak** [dynamicslab/hydrogym#193]
What solver should I use, since latest code does not include IPCS yet all the examples do?

Traceback (most recent call last):
  File "/IdeaProjects/hydrogym/examples/ppo/cyl.py", line 53, in <module>
    ppo.ppo(
  File "/IdeaProjects/hydrogym/examples/ppo/ppo.py", line 361, in ppo
    env = env_fn()
  File "/IdeaProjects/hydrogym/examples/ppo/cyl.py", line 54, in <lambda>
    lambda: gym.make("Cylinder-v0", env_config=env_config),
  File "/home/firedrake/firedrake/lib/python3.10/site-packages/gym/envs/registration.py", line 640, in make
    env = env_creator(**_kwargs)
  File "/IdeaProjects/hydrogym/examples/ppo/cyl.py", line 17, in __init__
    "solver": hydrogym.firedrake.IPCS,
AttributeError: module 'hydrogym.firedrake' has no attribute 'IPCS'

**Comment by ReHoss** [comment]
@dmitryshribak The examples are, unfortunately, outdated. You should use the semi-implicit solver from https://github.com/dynamicslab/hydrogym/blob/main/hydrogym/firedrake/solvers/bdf_ext.py

**Comment by ludgerpaehler** [comment]
We are currently fixing issues with the main core HydroGym code + its flow environments, and will then rewrite the examples (+notebooks).

I'm afraid it'll probably take +/- 1 month though..

**Comment by ludgerpaehler** [comment]
For documentation purposes, this is sort of what one should run:

```python
flow_dict = {
    "flow": hydrogym.firedrake.Cylinder,
    "flow_config": {
        "Re": args.reynolds_number,
        "mesh": args.mesh_resolution,
    },
    "solver": hydrogym.firedrake.SemiImplicitBDF,
    "solver_config": {
        "dt": args.time_step,
    },
    "callbacks": [log],
    "max_steps": 10000,
}
```

see here for a contained example: https://github.com/dynamicslab/hydrogym/blob/lp/bug-hunting/reproducer_rewrite_ppo_train.py

Will close this issue for now as the attached example and the staging branch fix it. Please feel free to reopen the issue if you run into the issue again.
